// <auto-generated />
namespace ThemeEmbeding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stoclin_stockout_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stoclin_stockout_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806302017245_stoclin_stockout_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
