// <auto-generated />
namespace ThemeEmbeding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderList_OrderStatus_Customer_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderList_OrderStatus_Customer_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201807181559023_OrderList_OrderStatus_Customer_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
