// <auto-generated />
namespace ThemeEmbeding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class p_c_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(p_c_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201806301945256_p_c_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
